import { ShipmentItem } from '@/types/shipment';

export const INITIAL_SHIPMENTS: ShipmentItem[] = [
  {
    id: 'FS-8821',
    cargo: 'beef',
    cargoNameEn: 'KazBeef Organic Beef',
    exporter: 'KazBeef Processing LLP',
    carrier: 'KTZ Express / ADY Multimodal',
    origin: 'Astana, Kazakhstan',
    destination: 'Dubai Logistics City, UAE',
    currentWaypoint: 'kuryk',
    waypointName: 'Port Kuryk Ferry Terminal',
    assetValueUsd: 72000,
    departureDate: '2026-09-24',
    eta: '2026-10-06 (7 Days)',
    bhi: 96.5,
    predictedRulHours: 440,
    status: 'OPTIMAL',
    telemetry: {
      temperature: 2.2,
      humidity: 85,
      ethanol: 4.2,
      vibration: 0.3,
    },
  },
  {
    id: 'FS-9042',
    cargo: 'berries',
    cargoNameEn: 'Altyn Dan Fresh Berries',
    exporter: 'Altyn Dan Agro Holdings',
    carrier: 'Caspian Bosphorus Reefer Line',
    origin: 'Almaty Agri-Valley, Kazakhstan',
    destination: 'Baku Agromarket, Azerbaijan',
    currentWaypoint: 'kuryk',
    waypointName: 'Port Kuryk Rail-Ferry Buffer',
    assetValueUsd: 48000,
    departureDate: '2026-09-26',
    eta: '2026-09-30 (1.5 Days)',
    bhi: 48.2,
    predictedRulHours: 28,
    status: 'CRITICAL',
    telemetry: {
      temperature: 7.8,
      humidity: 91,
      ethanol: 38.4,
      vibration: 0.8,
    },
    alert: {
      severity: 'CRITICAL',
      message: 'Volatile ethanol spike (38.4 ppm > 35 ppm threshold) detected at Port Kuryk rail-to-ferry transition. Accelerated fermentation underway.',
      timestamp: '12 min ago',
      action: 'Emergency cooling injection & priority ro-ro ferry boarding or immediate local cold storage transfer.',
      location: 'Port Kuryk Staging Buffer',
    },
  },
  {
    id: 'FS-4103',
    cargo: 'dairy',
    cargoNameEn: 'Saumal Bio-Kefir & Dairy',
    exporter: 'Eurasia Bio-Dairy LLC',
    carrier: 'Georgian Railways / Silk Road Trans',
    origin: 'Kostanay Region, Kazakhstan',
    destination: 'Poti Sea Port Terminal, Georgia',
    currentWaypoint: 'baku',
    waypointName: 'Port of Baku (Alat Hub)',
    assetValueUsd: 36000,
    departureDate: '2026-09-22',
    eta: '2026-10-02 (3.5 Days)',
    bhi: 68.4,
    predictedRulHours: 72,
    status: 'WARNING',
    telemetry: {
      temperature: 5.6,
      humidity: 79,
      ethanol: 16.2,
      vibration: 0.6,
    },
    alert: {
      severity: 'WARNING',
      message: 'Thermal drift detected during Caspian Sea crossing. Reefer ambient temperature elevated to +5.6°C.',
      timestamp: '42 min ago',
      action: 'Switch secondary auxiliary compressor cycle and verify shore-power receptacle at Alat terminal.',
      location: 'Port of Baku, Caspian Anchorage',
    },
  },
  {
    id: 'FS-6218',
    cargo: 'fruits',
    cargoNameEn: 'Tian Shan Organic Apples & Cherries',
    exporter: 'Zhetysu Orchards Consortium',
    carrier: 'Trans-Caucasus Intermodal',
    origin: 'Shymkent, Kazakhstan',
    destination: 'Istanbul Distribution Center, Turkey',
    currentWaypoint: 'poti',
    waypointName: 'Poti Intermodal Rail Yard',
    assetValueUsd: 54000,
    departureDate: '2026-09-20',
    eta: '2026-10-04 (5.5 Days)',
    bhi: 89.1,
    predictedRulHours: 216,
    status: 'OPTIMAL',
    telemetry: {
      temperature: 3.8,
      humidity: 88,
      ethanol: 8.5,
      vibration: 0.4,
    },
  },
  {
    id: 'FS-3319',
    cargo: 'beef',
    cargoNameEn: 'Steppe Prime Chilled Lamb Cuts',
    exporter: 'Batys Agro Export',
    carrier: 'Aktau Logistics Marine Fleet',
    origin: 'Uralsk, Kazakhstan',
    destination: 'Doha Commercial Port, Qatar',
    currentWaypoint: 'istanbul',
    waypointName: 'Marmara Transit Corridor',
    assetValueUsd: 85000,
    departureDate: '2026-09-18',
    eta: '2026-10-08 (9 Days)',
    bhi: 98.2,
    predictedRulHours: 510,
    status: 'OPTIMAL',
    telemetry: {
      temperature: 1.8,
      humidity: 84,
      ethanol: 3.1,
      vibration: 0.2,
    },
  },
  {
    id: 'FS-7750',
    cargo: 'dairy',
    cargoNameEn: 'Amiran Infant Formula & Yogurt',
    exporter: 'Amiran Dairy Corporation',
    carrier: 'KTZ Reefer Fleet Services',
    origin: 'Almaty, Kazakhstan',
    destination: 'Tbilisi Food Terminal, Georgia',
    currentWaypoint: 'baku',
    waypointName: 'Baku Alat Inland Dry Port',
    assetValueUsd: 42000,
    departureDate: '2026-09-25',
    eta: '2026-10-01 (2.5 Days)',
    bhi: 58.0,
    predictedRulHours: 42,
    status: 'WARNING',
    telemetry: {
      temperature: 8.4,
      humidity: 81,
      ethanol: 22.4,
      vibration: 0.9,
    },
    alert: {
      severity: 'WARNING',
      message: 'Reefer unit compressor intermittent fault. Temperature reached +8.4°C under high ambient staging temperature.',
      timestamp: '1 hour ago',
      action: 'Dispatch on-call mobile technician at Alat Dry Port for coolant pressure valve inspection.',
      location: 'Baku Alat Inland Dry Port',
    },
  },
];

export function getShipmentById(id: string): ShipmentItem | undefined {
  return INITIAL_SHIPMENTS.find((s) => s.id.toLowerCase() === id.toLowerCase());
}
